  - label: ":ios::react: RN .72 + iOS: Demo app"
    command:
      - "nvm install"
      - "xcrun simctl create 'iPhone 12 Pro Max' 'com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro-Max'"
      - "./scripts/demo-projects.ios.sh"
    env:
      REACT_NATIVE_VERSION: 0.72.8
    artifact_paths:
      - "/Users/builder/work/coverage/**/*.lcov"
      - "/Users/builder/work/artifacts*.tar.gz"
    agents:
        queue: uibuilder
